---
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
    - /var/log/*.json

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "elastic"

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "elastic"
